#Vanilla Exp Multipler
#Made by MuchDan
#11/6/20
#For Detailed information, View decompiled Notes text file.


#Begin Configuration File
Verbose: false  #Prints the multiplier, original value, and rounded value to console when exp is gained.
#Permission node to set player multipliers.
SetMultiplier: Admin.SetMultiplier

#When unauthorized player gets denied.
DenyMessage: "&cYou don't have permission to do that!"

#Player Message when Multiplier is applied
Applied-Message: "&b<Multiplier>x Multiplier has been successfully applied!"

#Multipliers can be named anything, these are referenced in command /setMultiplier MuchDan Level1
Multipliers:
  Level1:
    Multiplier: 1.5
  Level2:
    Multiplier: 2.0
  Level3:
    Multiplier: 3.0
  Level4:
    Multiplier: 4.0